CREATE TABLE PATIENTS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PATIENT_ID VARCHAR(12) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    DOB DATE,
    ADDRESS VARCHAR(1000),
    PHONE_NUMBER VARCHAR(20),
    PRIMARY KEY(id)
);